# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app2
  labels:
    project: roboshop
    purpose: ingress-demo
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      purpose: ingress-demo
      app: app2
  template:
    metadata:
      labels:
          project: roboshop
          purpose: ingress-demo
          app: app2
    spec:
      containers:
        - name: app2
          image: kirankumarkosuri/app2:v1
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    project: roboshop
    purpose: ingress-demo
    app: app2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# Ingress Controller
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:396199428170:certificate/1039818d-3829-41b8-80f5-c8b62d2f260d
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: roboshop
spec:
  ingressClassName: alb
  rules:
  - host: "app2.daws86s.blog"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80



