apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # these are replica set labels
  labels:
    purpose: ingress-demo
    project: roboshop
    app: app1
spec:
  replicas: 2
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: ingress-demo
      project: roboshop
      app: app1
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: ingress-demo
        project: roboshop
        app: app1
    spec:
      containers:
      - name: app1
        image: kirankumarkosuri/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    project: roboshop
    purpose: ingress-demo
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:396199428170:certificate/03de318c-1db6-4d43-8dae-59db77c742ae
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
spec:
  ingressClassName: alb
  rules:
  - host: "app1.daws86s.blog"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80
